/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'

import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

import modelURI from './model.glb'

console.log(modelURI)

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useLoader<any>(GLTFLoader, modelURI)

  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="Default" userData={{ name: 'Default' }}>
          <group
            name="model"
            position={[0, 2.3, 2.5]}
            rotation={[-Math.PI / 2, 0, 0]}
            userData={{ name: 'model' }}
          >
            <group name="model_1" userData={{ name: 'model' }}>
              <mesh
                name="model_5"
                material={nodes.model_5.material}
                geometry={nodes.model_5.geometry}
                userData={{ name: 'model' }}
              />
            </group>
            <group name="model_2" userData={{ name: 'model' }}>
              <mesh
                name="model_6"
                material={nodes.model_6.material}
                geometry={nodes.model_6.geometry}
                userData={{ name: 'model' }}
              />
            </group>
            <group name="model_3" userData={{ name: 'model' }}>
              <mesh
                name="model_7"
                material={nodes.model_7.material}
                geometry={nodes.model_7.geometry}
                userData={{ name: 'model' }}
              />
            </group>
            <group name="model_4" userData={{ name: 'model' }}>
              <mesh
                name="model_8"
                material={nodes.model_8.material}
                geometry={nodes.model_8.geometry}
                userData={{ name: 'model' }}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}
